// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVCB7X9xp1JivFb4x2as57HgKr3zIcA7Q',
    appId: '1:190739138652:web:23974e44ac595770befe99',
    messagingSenderId: '190739138652',
    projectId: 'fito-71fc9',
    authDomain: 'fito-71fc9.firebaseapp.com',
    storageBucket: 'fito-71fc9.appspot.com',
    measurementId: 'G-TTWH7HKTET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcRY0n4swKPpqDRT9RIwcc9_43-mYDUHo',
    appId: '1:190739138652:android:cf047c8af4fbf316befe99',
    messagingSenderId: '190739138652',
    projectId: 'fito-71fc9',
    storageBucket: 'fito-71fc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfb2AII1lkzxv1AR8-MIUpSAa-QeNlZYY',
    appId: '1:190739138652:ios:2972e3e5be0c300ebefe99',
    messagingSenderId: '190739138652',
    projectId: 'fito-71fc9',
    storageBucket: 'fito-71fc9.appspot.com',
    iosClientId:
        '190739138652-vtgth53pr5td5dvng1nosgdvfjmmutvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfb2AII1lkzxv1AR8-MIUpSAa-QeNlZYY',
    appId: '1:190739138652:ios:2972e3e5be0c300ebefe99',
    messagingSenderId: '190739138652',
    projectId: 'fito-71fc9',
    storageBucket: 'fito-71fc9.appspot.com',
    iosClientId:
        '190739138652-vtgth53pr5td5dvng1nosgdvfjmmutvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackApp',
  );
}
